# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UG1nTaCce79JO8RAmZcxBAqM9QyBrqgC
"""

import numpy as np
import pandas as pd

df = pd.read_csv("api_data_aadhar_enrolment_0_500000.csv")

print(df.shape)

print(df.info())

print(df.isnull().sum)

print(df.duplicated().sum())

df = df.drop_duplicates()

print(df.shape)

print("Current data types:\n", df.dtypes)

df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['state'] = df['state'].astype('category')

df['district'] = df['district'].astype('category')

df['pincode'] = df['pincode'].astype(str)

print("Updated data types:\n", df.dtypes)

invalid_dates = df[df['date'].isna()]

print(f"Number of rows with invalid or missing dates: {len(invalid_dates)}")

age_cols = ['age_0_5', 'age_5_17', 'age_18_greater']

df['total_enrolments'] = df[age_cols].sum(axis=1)

state_total_enrolments = df.groupby('state')['total_enrolments'].sum().reset_index()

df['total_enrolments'] = df[age_cols].sum(axis=1)

state_total_enrolments = state_total_enrolments.sort_values(by='total_enrolments', ascending=False)

print(state_total_enrolments)

df = df[df["state"].str.contains("[A-Za-z]")]

df['state'] = df['state'].replace({
    'Andaman & Nicobar Islands': 'Andaman and Nicobar Islands',
    'Westbengal': 'West Bengal',
    'West Bangal': 'West Bengal',
    'WEST BENGAL': 'West Bengal',
    'West  Bengal': 'West Bengal',
    'West bengal': 'West Bengal',
    'andhra pradesh': 'Andhra Pradesh',
    'ODISHA': 'Odisha',
    'Orissa': 'Odisha',
    'Jammu & Kashmir': 'Jammu and Kashmir',
    'Jammu And Kashmir': 'Jammu and Kashmir',
    'Dadra & Nagar Haveli': 'Dadra and Nagar Haveli',
    'The Dadra And Nagar Haveli And Daman And Diu': 'Dadra and Nagar Haveli and Daman and Diu',
    'Dadra and Nagar Haveli and Daman and Diu': 'Dadra and Nagar Haveli and Daman and Diu',
    'Daman & Diu': 'Daman and Diu',
    'Pondicherry': 'Puducherry'
})

state_age_total = df.groupby('state')[age_cols].sum()
state_age_total['total_enrolments'] = state_age_total.sum(axis=1)

for col in age_cols:
    state_age_total[col + '_percent'] = (state_age_total[col] / state_age_total['total_enrolments']) * 100

state_age_total = state_age_total.reset_index()

print(state_age_total)

df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
monthly_enrolment_trend = (
    df.groupby(['state', 'month'])['total_enrolments']
      .sum().reset_index())

print(monthly_enrolment_trend.head())

import matplotlib.pyplot as plt

state_name = 'Uttar Pradesh'

state_monthly = monthly_enrolment_trend[
monthly_enrolment_trend['state'] == state_name
]

plt.figure(figsize=(8, 5))
plt.figure(figsize=(8, 5))
plt.plot(
state_monthly['month'],
state_monthly['total_enrolments'],
marker='o'
)
plt.title(f'Monthly Aadhaar Enrolment Trend – {state_name}')
plt.xlabel('Month')
plt.ylabel('Total Enrolments')
plt.grid(True)
plt.show()

top10_states = state_total_enrolments.head(10)

plt.figure(figsize=(10, 6))
plt.barh(top10_states['state'], top10_states['total_enrolments'])
plt.title('Top 10 States by Aadhaar Enrolments')
plt.xlabel('Total Enrolments')
plt.ylabel('State')
plt.gca().invert_yaxis()
plt.show()

top_states_age = state_age_total.sort_values(
    'total_enrolments', ascending=False
).head(8)

plt.figure(figsize=(10, 6))
plt.bar(top_states_age['state'], top_states_age['age_0_5_percent'], label='0–5')
plt.bar(top_states_age['state'], top_states_age['age_5_17_percent'],
        bottom=top_states_age['age_0_5_percent'], label='5–17')
plt.bar(top_states_age['state'], top_states_age['age_18_greater_percent'],
        bottom=top_states_age['age_0_5_percent'] + top_states_age['age_5_17_percent'],
        label='18+')

plt.title('Age-wise Aadhaar Enrolment Composition (Top States)')
plt.ylabel('Percentage')
plt.xticks(rotation=45)
plt.legend()
plt.show()
national_monthly = (
df.groupby('month')['total_enrolments']
.sum()
.reset_index()
)

plt.figure(figsize=(8, 5))
plt.plot(national_monthly['month'], national_monthly['total_enrolments'], marker='o')
plt.title('National Monthly Aadhaar Enrolment Trend')
plt.xlabel('Month')
plt.ylabel('Total Enrolments')
plt.grid(True)
plt.show()
top_districts = (
df.groupby('district')['total_enrolments']
.sum()
.reset_index()
.sort_values(by='total_enrolments', ascending=False)
.head(10)
)

plt.figure(figsize=(10, 6))
plt.barh(top_districts['district'], top_districts['total_enrolments'])
plt.title('Top 10 Districts by Aadhaar Enrolments')
plt.xlabel('Total Enrolments')
plt.gca().invert_yaxis()
plt.show()
state_total_enrolments = df.groupby('state')['total_enrolments'].sum().reset_index()
state_total_enrolments = state_total_enrolments.sort_values(by='total_enrolments', ascending=False)

# Get bottom 10 states
bottom_10_states = state_total_enrolments.tail(10).sort_values(by='total_enrolments', ascending=True)

plt.figure(figsize=(10, 6))
plt.barh(bottom_10_states['state'], bottom_10_states['total_enrolments'], color='#e74c3c')
plt.title('Bottom 10 States by Aadhaar Enrolments - Priority Intervention Areas',
           fontsize=14, fontweight='bold')
plt.xlabel('Total Enrolments', fontsize=12)
plt.ylabel('State', fontsize=12)
plt.tight_layout()
plt.show()

print("Bottom 10 States requiring priority intervention:")
print(bottom_10_states)
national_age_total = df[age_cols].sum()
national_age_percent = (national_age_total / national_age_total.sum()) * 100

plt.figure(figsize=(8, 8))
colors = ['#e74c3c', '#f39c12', '#2ecc71']
explode = (0.1, 0.05, 0)  # Explode first slice to highlight gap

plt.pie(national_age_percent, labels=['0-5 years', '5-17 years', '18+ years'],
         autopct='%1.1f%%', startangle=90, colors=colors, explode=explode,
         textprops={'fontsize': 12, 'fontweight': 'bold'})
plt.title('National Age Distribution in Aadhaar Enrolments\n(Note: Low 0-5 representation)',
          fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

print("\nNational age distribution:")
print(national_age_percent)